### ISSUE TITLE
rotateLeftBy

### ISSUE THREAD

**Issue by farism** [ktonon/elm-word#1]
Hey, first off great library!

I was wondering if there were any plans to implement `rotateLeftBy`? I don't think it would be hard to implement it in my application code for now but it would be cool if it lived here. Thanks!

**Comment by ktonon** [comment]
Implemented as rotate right `wordSizeInBits - n`. Added unit tests. 9b5641b49e8fe128bc7d1d7306453de4416a7ddb

**Comment by ktonon** [comment]
Published to `2.1.0`

**Comment by farism** [comment]
Thanks again!
